### PR TITLE
Add <Context> path attribute as a parameter for jira class

### PR DESCRIPTION
**Pull request by poikilotherm**
This PR will add template code to be able to add a context path for the JIRA Tomcat instance. 

I need this in companion with my reverse proxy, as I have a context path in my apache in which I add the reverse proxy configuration.

I added some validations in init.pp, too. (For $contextpath, $proxy and $db).

### CODE REVIEW

**Comment by mkrakowitzer** [comment]
Thank you :) Would you consider taking a stab at adding some tests. 

I recently added the context path to the stash module, so you could use that as an example:
https://github.com/mkrakowitzer/puppet-stash/blob/master/spec/classes/stash_config_spec.rb

**Comment by poikilotherm** [comment]
Yeah sure, I'll write a test...
I just thought there are currently none and I did not want to get in someones way... ;-)

**Comment by poikilotherm** [comment]
I eat my words...
Of course there were already spec tests, just been dazzled.

I added the test for the context path.

Slightly off-topic: would you like me to refactor the init.pp and params.pp? I have some ideas for that... I'll gladly open an issue to sum them up.

**Comment by mkrakowitzer** [comment]
Certainly open to it, I would say open an issue and we take it from there.

Thanks for your contributions. Oh and please consider rating the Module on the forge if you have the time :)

Ill get this merged ASAP, just want to run it through my beaker tests, altough its a no brainer it will pass.

**Pull request merged**
